repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: "v0.2.2"
    hooks:
     - id: ruff
       args: [ --fix ]
     - id: ruff-format

  - repo: local
    hooks:
      - id: check-submodules
        name: Check and Update Submodules
        entry: scripts/update_submodules.sh
        language: script
        always_run: true
        stages: [commit]