name: request-driven-submodule-update

on:
  workflow_dispatch:
  repository_dispatch:
    types: [
      submodule_update
    ]

jobs:
  update-submodule:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout main repository
        uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Verify Payload
        run: |
          echo ${{ github.event.client_payload }}

      - name: Update specific submodule
        run: |
          SUBMODULE=${{ github.event.client_payload.submodule }}
          BRANCH=${{ github.event.client_payload.branch }}
          
          # Checkout the frontend branch that mirrors the submodule branch
          git checkout ${{ github.event.client_payload.branch }}
          
          # Update the latest submodules from the remote
          if [ "$SUBMODULE" == "flexcompute/tidy3d-notebooks" ]; then
            cd docs/notebooks
            git checkout $BRANCH
            git pull origin $BRANCH
            
            cd ../../
            git add docs/notebooks
          
          elif [ "$SUBMODULE" == "flexcompute/tidy3d-faq" ]; then
            cd docs/faq
            git checkout $BRANCH
            git pull origin $BRANCH
            cd ../../
            git add docs/faq
          
          else
            echo "Submodule $SUBMODULE not recognized. Debug the request."
            exit 1
          
          fi
          
          git commit -m ":robot: Automatic submodule $SUBMODULE update triggered from branch $BRANCH"
          
          # Update corresponding branch
          git push origin HEAD
